<?xml version="1.0" encoding="utf-8"?><Database Name="PokerFil" Class="DataClassesDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=.\SQLEXPRESS;Initial Catalog=PokerFil;User ID=admin" SettingsObjectName="PokeFil.Properties.Settings" SettingsPropertyName="PokerFilConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.PreflopProbility" Member="PreflopProbility">
    <Type Name="PreflopProbility">
      <Column Name="Id" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Hash" Type="System.Data.Linq.Binary" DbType="Binary(8) NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="WinProbility" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="SplitProbility" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="OtherPlayersCount" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Cards" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
</Database>